### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by dm0-** [rust-vmm/vm-allocator#53]
I was reviewing crate licenses and encountered three issues here:

- [ ] The `allocation_engine` files declare `SPDX-License-Identifier: Apache-2`, but the [SPDX ID](https://spdx.org/licenses) is `Apache-2.0`.
- [ ] Both the Cargo.toml file and README says the project is dual licensed (`Apache-2.0` or `BSD-3-Clause`), but the crate includes multiple files that are `Apache-2.0`-only, e.g. [`src/lib.rs`](https://github.com/rust-vmm/vm-allocator/blob/v0.1.0/src/lib.rs#L2).  Should the crate license be just `Apache-2.0` and maybe mention there are some dual-licensed source files in the README?
- [ ] The BSD license text is missing.  Can a file `LICENSE-BSD-3-Clause` be added to the crate?

**Comment by dm0-** [comment]
Can you confirm if this file is the full text of the BSD license that would be added (or if not, what would it be)?

https://github.com/rust-vmm/crate-template/blob/803b14f79f089dc4cdb5356375c94081e29a5c30/LICENSE-BSD-3-Clause

It is not possible to follow the terms of this license without including the full text, but I could add it to distributions myself if you verify the text is correct.  Thanks.

**Comment by AlexandruCihodaru** [comment]
Hey, I will create a PR by the end of this week. Thanks :D
