### ISSUE TITLE
vm-allocator requirement and usage discussion

### ISSUE THREAD

**Issue by studychao** [rust-vmm/vm-allocator#8]
Hi, I'm Chao 😄
I would like to initiate the discussion about the requirement and usage of vm-allocator.

## The Big Picture
To start with a big picture, we think vm-allocator should be used for managing (allocating + releasing + tracking) **guest resource** for other components who need **guest resource**. vm-allocator is responsible for tracking all the resource usage and other components implements methods to access or control resources allocated from vm-allocator.

We think there are 2 main concepts needed clerification in vm-allocator design : resource and allocator  

## Resource
Resource should be managed by vm-allocator and let vm-allocator keep track of the resource usage.

After skimming through several VMM, resource here could be 3 kinds : 
1. ID resource. e.g. PCI device id
2. Memory resource. e.g. MMIO, PIO address space
3. Interrupt resource. e.g. msi irq

We should have an allocator general enough to allocate all those kinds of resource so that we don't need a new struct for every kind of resource.

## Allocator

Allocator is used to manage (allocate + release + track) the resource.
Allocator itself should have a range/pool for maximum resource to be allocated.

### How to ask for the resource allocation
We think there should be a **constraint** for other components to ask for resource from vm-allocator.

Constraint should describe the size of the resource it wants, the lower boundary it wants for the resource from the resource pool (optional), the upper boundary(optional) and the alignment(optional)

Once components could clearly describe the constraint for the resource they need, vm-allocator could find the most appropriate resource for them.

### How to ask for the resource release

Other components could give the exact resource(e.g. address space range, id number) / device name/device struct to let vm-allocator know which resource to release.

### How to allocate, release and track resource

Resource Allocation should follow these rules:
1. Different allocations should not overlay with each other.
2. Resource allocations shouldn't pass the lower and upper bound.
3. Resource allocations should follow the description of the **constraint**

Resource Release will free the resource range from the resource pool and other allocation could use that range.

Recource Track means vm-allocator should have the ability to query for the resource.

## Summary
As the conclusion, the vm-allocator would be made of one allocator for managing resource and constraint for describing the resource needed.

**Comment by studychao** [comment]
@jiangliu @andreeaflorescu Please let me know your thoughts on this:)

**Comment by jiangliu** [comment]
> I have a question, what is the connection (if any) between the constraint that you are taking about here and the ones defined in vm-device: https://github.com/rust-vmm/vm-device/blob/main/src/resources.rs#L18

Basically it should support/respect all resource constraints defined in vm-device crate, but it also need to support more resource types/constraints such as pci device number. The vm-device crate defines resources may be requested by a device, but there are more resource types needed by the vmm.

**Comment by jiangliu** [comment]
> > I have a question, what is the connection (if any) between the constraint that you are taking about here and the ones defined in vm-device: https://github.com/rust-vmm/vm-device/blob/main/src/resources.rs#L18
> 
> Basically it should support/respect all resource constraints defined in vm-device crate, but it also need to support more resource types/constraints such as pci device number. The vm-device crate defines resources may be requested by a device, but there are more resource types needed by the vmm.

For example, we need to explicitly allocate/free GPA for guest memory too.

**Comment by studychao** [comment]
Hi @alsrdn , thanks for your detailed reply :)

Please give me 1~2 days to look at the code and consider about our design. I'll reach back to you soon~

**Comment by studychao** [comment]
Hi @alsrdn Here is my thoughts .

> I guess that it should be also able to update them if needed. 

Yes, I miss the update part in the original issue. I have updated the issue, thanks for reminding me.

> Is it a hard requirement to have a single struct for everything?

> Shouldn’t the constraint actually be dependant on the type of resource allocated? We can have the allocate function implemented using a generic type that allows the user to specify custom constraints. It might not make sense for all constraints to have the same definition (e.g. what is the upper boundary used for or why would one need alignment for interrupt numbers)

The constraint in our design is pretty flexible. Only size is a must to do constraint::new() and alignment/upper boundary/lower boundary is optional . What we are trying to do here is when user wants to have some resource, we have one unified approach to describe the resource constraint.

From your demo, the AddressAllocator allocates with resource's address, size and alignment(memory_range_tag could be tagged by allocator), GsiAllocator allocates resource using Btreeset freed_gsi or next_gsi (implies size = 1). Those allocation requirements could be described using Constraint (size+alignment constraint for the first and size constraint for the second).

Besides, allocator itself could have some allocation pattern or rule (e.g. allocate the resource in ascending order )so that we don't need to implement freed_gis/next_gsi manually. 

> We need to clarify what interrupt resource means here. From previous discussions it seems like the function of this allocator would be to provide only GSI numbers. 

Agree:). Besides, from my view, GSI number is related to ID allocation and all other ID related allocation could also use vm-allocator to allocate, release and track if needed.

> Apart from allocating MMIO/PIO address space, we would also need the ability to map memory and expose these ranges to the guest. E.g. for PCI passthrough we want to be able to map device BARs into the address space that was allocated. We think this should be a function of the Address space allocator as well since it is the one keeping track of all available Addresses.

Yes, this could also be allocated by the vm-allocator.


> Wouldn’t the PCI ID (BDF) of the device be given by the PCI topology? E.g. if a device is added on the first slot of the first PCI Bus, wouldn’t its id be 00:01.0? 

I think PCI topology could be used to describe what PCI resource constraint is so that vm-allocator could also be used to allocate the PCI ID resource.

---


From your code draft, there are 2 allocator: AddressAllocator and GsiAllocator. Our design have one allocator and one constraint for describing the resource needed. I think this is the biggest divergence between your design and ours.

What we are trying to do is to have one allocator generic enough to allocate, release and track different kinds of resource which meet the description of constraint. So that vm-allocator as a lib don't need to develop different kinds of allocator for different resource which will add complexity and reduce compatibility.

Take GsiAllocator from your design as an example, if users want to allocate other ID related resource, it's illogical for them to use GsiAllocator. So another allocator needs to be added or GsiAllocator needs to be optimized to IDAllocator.

If GsiAllocator could be generic to an IDAllocator, we think AddressAllocator + IDAllocator could be more generic to one allocator because IDAllocator is the special case when resource size equals 1 for AddressAllocator.

So whether should we have one generic allocator or different allocators is the important problem we need to figure out.:)

**Comment by AlexandruCihodaru** [comment]
Hello @studychao thank you for your reply. As you have mentioned here

> Take GsiAllocator from your design as an example, if users want to allocate other ID related resource, it's illogical for them to use GsiAllocator. So another allocator needs to be added or GsiAllocator needs to be optimized to IDAllocator.

The GSIAllocator should indeed be renamed to IDAllocator since the interrupt numbers are just an ID that is used to identify an interrupt. This IDAllocator can be used to also allocate KVM memory slot IDs, PCI device IDs and so on. Although the current proposal works fine for objects that can be reduced to an u64, extending it to allocate other other types of resources like GUIDs(that are u128) or string names will break the Open-Closed principle. To respect the interface segregation principle as well we believe that an approach where we have two allocators one for IDs and one for Addresses would be a better fit. Having two allocators each one with its specialised usage would bring in more type safety and allow us to carry with us just the information that is necessary for each resource type.

**Comment by AlexandruCihodaru** [comment]
Hello @studychao @jiangliu, to move forward with this issue we will make a proposal where we have two separate allocators one for IDs and one for Addresses. The allocator for Addresses will use as an allocation engine the IntervalTree implementation that @studychao  proposed in PR#7. Are you onboard with this?

**Comment by AlexandruCihodaru** [comment]
Closing this as we identified a path forward.
